server:
  port: 8202
 
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: forest
    timeout: 2000
    jedis:
      pool:
        max-idle: 8000
        max-wait: -1
        max-active: -1
        min-idle: 200  application:    name: forest-system-web
eureka:
  instance:
    prefer-ip-address: true
    instance-id: localhost:${server.port}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      