spring:
  profiles:
    active: dev
  application:
    name: forest-system-web

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true