spring:
  profiles:
    active: dev
  application:
    name: forest-mall-server

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


mybatis-plus:
  mapper-locations: cn/forest/mall/mapper/xml/*.xml
  type-aliases-package: cn.forest.mall.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
logging:
  level:
    cn.forest.mall.mapper: debug


    




      
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      