server:
  port: 5401
  
eureka:
  instance:
    prefer-ip-address: true
    instance-id: localhost:${server.port}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://test02:7777/eureka/eureka,http://test04:7777/eureka/eureka


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.7:3306/complex-system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: jft
    password: LOXxdAv3Eo57moV9jw9JdJ2Si6tG0gkJSeYMGZJanxpuoorC+NbSaBx1bq5ro9Hf3jBx4ssv504aRFZTzvL3wg==
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKkTY4rjSwwojtAR/loSeXdVJjQNMpqh89j7jB83O0yQgupc2o0Tc67CFufo07sS/rQXIWqRxii5b92mwDANE6MCAwEAAQ==
    druid:
      initial-size: 1
      max-active: 20
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publickey}