server:
    port: 8210

eureka:
  instance:
    prefer-ip-address: true
    instance-id: localhost:${server.port}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/

file-site-path: http://image.jf.jf180.vip
oss-path: http://oss-cn-beijing.aliyuncs.com
upload-base-path: /data/java_upload_file
file-upload-path: upload/file/
image-upload-path: upload/image/
