server:
  port: 8301
  
eureka:
  instance:
    prefer-ip-address: true
    instance-id: localhost:${server.port}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/


spring:
  application:
    name: forest-system-server
  datasource:
           #是否开启读写分离 false 不开启，true 开启
    r-w-separation: false
    names: slave1
    master:      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/complex-system
      username: root
      password: root
      druid:        initial-size: 1
        max-active: 20
    slave1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/complex-system-cluster
      username: root
      password: root
      druid:
        initial-size: 1
        max-active: 20
      
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


mybatis-plus:
  mapper-locations: cn/forest/system/mapper/xml/*.xml
  type-aliases-package: www.forest.system.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql


    




      
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      