spring:
  profiles:
    active: prod
  application:
    name: forest-system-server

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


mybatis-plus:
  mapper-locations: cn/forest/system/mapper/xml/*.xml
  type-aliases-package: cn.forest.system.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # mybatis-plus 打印完整日志
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
logging:
  level:
    cn.forest.system.mapper: debug