server:
  port: 8501
  
eureka:
  instance:
    prefer-ip-address: true
    instance-id: localhost:${server.port}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/


spring:
  application:
    name: forest-mall-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/complex-system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: HHIHnfUqbly3dwh41Ydf/VJdOCWaXJEiN0II+Ptu0LbRnhTrcZzA9cv5lhlMl85iv+pUydJG+kLdB/73ivRY6w==
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKJ9MuOPaeuBMb7wL9izzGlTk4glfLYPynFgh2NsP7S7oOi6ltOn1QBU1UEJzn5h3Bk552pwxAgY3N/IYI4eQkcCAwEAAQ==
    druid:
      initial-size: 1
      max-active: 20
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publickey}
      
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


mybatis-plus:
  mapper-locations: cn/forest/mall/mapper/xml/*.xml
  type-aliases-package: cn.forest.mall.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
logging:
  level:
    cn.forest.mall.mapper: debug


    




      
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      