server:
  port: 8501
  
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://server01.i.jf180.cn:7777/eureka/eureka,http://server02.i.jf180.cn:7777/eureka/eureka

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2zeazd9324lq3p914.mysql.rds.aliyuncs.com:3306/complex-system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: user_merchnt
    password: BP0KU/85SgCFETeYZ/fDD02xhIwWe5qOTbSNtbuLTh6DOAev331YFLcPeGJALiPJYmU/6wQOcrDBOfRHxNYdzg==
    publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAK9/HgwZASVZzS3QI3B52youSVVYgZIB8xETl2Qn5JUc5MsK4zZLxiQt+behdNVCBTiDbKsaxbnWNd2MpqUqiF0CAwEAAQ==
    druid:
      initial-size: 1
      max-active: 20
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.publickey}