
spring:
  profiles:
    active: prod
  application:
    name: forest-login-web
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      
feign:
  hystrix:
    enabled: true